  name: Deploy Decoletech Frontend Platform

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.project_id }}
          service_account_key: ${{ secrets.GOOGLE_CREDENTIALS}}
          install_components: "gke-gcloud-auth-plugin"
          export_default_credentials: true

      - name: Authenticate Docker with Artifact Registry
        run: |
          gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet

      - name: Build and Push Docker Images
        run: |
          docker build -t europe-west3-docker.pkg.dev/${{ secrets.project_id }}/decoletech/nextjs:v1 .
          docker push europe-west3-docker.pkg.dev/${{ secrets.project_id }}/decoletech/nextjs:v1

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials autopilot-cluster-1 --region us-central1

      - name: Deploy Kubernetes Manifests
        run: |
          kubectl apply -f ./k8s/nextjs.yaml
