name: Deploy Decoletech Frontend Platform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Updated to latest version

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2 # Updated to latest version
        with:
<<<<<<< HEAD
          project_id: ${{ secrets.PROJECT_ID }} # Use uppercase for consistency
=======
          project_id: ${{ secrets.project_id }}  # Use uppercase for consistency
>>>>>>> dc950dd1bf52cbcfbdbb2e31f850ab7511fd22bd
          service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
          install_components: gke-gcloud-auth-plugin
          export_default_credentials: true

      - name: Authenticate Docker with Artifact Registry
        run: |
          gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet

      - name: Build and Push Docker Images
<<<<<<< HEAD

        run: |
          docker build -t europe-west3-docker.pkg.dev/${{ secrets.PROJECT_ID }}/decoletech/nextjs:latest .
          docker push europe-west3-docker.pkg.dev/${{ secrets.PROJECT_ID }}/decoletech/nextjs:latest
=======
       
        run: |
          docker build -t europe-west3-docker.pkg.dev/${{ secrets.project_id }}/decoletech/nextjs:latest .
          docker push europe-west3-docker.pkg.dev/${{ secrets.project_id }}/decoletech/nextjs:latest
>>>>>>> dc950dd1bf52cbcfbdbb2e31f850ab7511fd22bd

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials autopilot-cluster-1 --region us-central1

      - name: Deploy Kubernetes Manifests
        env:
          IMAGE_TAG: ${{ secrets.PROJECT_ID }}
        run: |
          # Replace image tag in manifest before applying
          sed -i "s|GOOGLE_PROJECT|${IMAGE_TAG}|g" ./k8s/nextjs.yaml
          kubectl apply -f ./k8s/nextjs.yaml
